name = "community-carehub-backend"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "carehub_db"
database_id = "6b52c7a1-0720-4cff-9e78-82f0f78841ad"
